name: Publish NPM

on:
  push:
    tags:
    - '*'

jobs:
  npm:
    name: NPM Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install
        run: npm install
      - name: Change Package version
        run: ./utils/version-from-tag.js
      - name: Publish
        run: |
          export NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
          npm publish
